IEEE-VIT/back-to-future

- Go/binarysearch.go
A Binary Search Algorithm using Golang
> A Binary Search Algorithm using Golang

- Java/CheckPrime.java
Add implementation code to check prime numbers
> fix: implementation java algorithm to check prime number

- C++/binarysearch.cpp
- C++/binarytree.cpp
- C++/bubblesort.cpp
- C++/checkPrime.cpp
- C++/eval.cpp
- C++/fibonacci.cpp
- C++/heapsort.cpp
- C++/infixtopostfix.cpp
- C++/selectionsort.cpp
Completed algorithm present in c++ repository to resolve issue assigned.
@axrav
> Solving Algorithms C++

- Rust/binarysearch.rs
- Rust/bubblesort.rs
- Rust/checkprime.rs
- Rust/fibonacci.rs
- Rust/heapsort.rs
- Rust/selectionsort.rs
binarysearch
bubblesort
checkprime
fibonacci
heapsort
selectionsort
> Implemented the following in rust 

- C++/linkedlist.cpp
- README.md
Added Linked List with the basic functions of addAtEnd, getLastNode, search, isEmpty, length. And some advanced functions for solving some DSA questions, eg. reverseList, reverseListRecursively, reverseK, findIntersection, mergeSortedLists, etc.
> add: Linked List

- Javascript/quicksort.js
Thanks for reading my pull request.
> Added quick sort.js

- Javascript/binarysearch.js
- Javascript/bubblesort.js
- Javascript/checkprime.js
- Javascript/fibonacci.js
- Javascript/heapsort.js
- Javascript/mergesort.js
- Javascript/selectionsort.js
Added the code of following algorithms in JS : 
1. Selection Sort
2. Merge Sort
3. Bubble Sort
4. Binary Search
5. Heap Sort
6. Binary Search
> Completed some JS algorithms

- C/selectionsort.c
added selectionsort implementation in c
> add: selectionsort

- C/binarysearch.c
add binarysearch implemantation in c
> add: binarysearch-c

- C++/mergeSort.cpp
Greeting sir , I added a Merge sort algorithm code. Feel free to "Merge" it :)
> Merge Sort Algorithm in C++

- Python/heapsort.py
Implemented python program on heap sort
> Implemented heap sort in python

- C++/A_star.cpp
- README.md
> add program to implement A* algorithm in c++

- Javascript/BST_implementation.js
- Javascript/BST_search.js
- README.md
Added two programs : 
1. BST Implementation
2. BST Searching
> Added BST in js (also updated readme file)

- C/fibonacci.c
add fibonacci implementation in c
> add-fibonacci-c

- C/bubblesort.c
add bubbelsort implementation for c
> add-bubbelsort-c

- C++/radix_sort.cpp
> Added-Radix-sort.cpp !

- C++/binarySearchTree.cpp
- C++/quicksort.cpp
Algorithm for quick sort in c++
> Added new: Quick Sort Algo

- Python/insertion_sort.py
Added python code for insertion sort
> Insertion Sort

- C/Armstrong.c
> C code for Armstrong Number created

- Javascript/quicksort.js
- Javascript/shuffle_a_deck_of_cards.js
- README.md
Thanks for considering my request.
> Added_Shuffle_a_deck_of_cards.js

- Go/fibonacci.go
Implementing fibonacci in golang :)
> feat: fibonacci in golang

- Python/mergesort.py
@axrav I've implemented merge sort using python. Please have a look.
> ISSUE11: Added mergesort.py

- Python/armstrong.py
@axrav I've implemented Armstrong number program in python. Please have a look.
> ISSUE11:Added armstrong.py

- C++/TopologicalSort.cpp
Topological Sort for Graph Algorithm Implemented and tested
> Added Topological Sort for Graph Algorithm

- C++/CycleDetectionGraph.cpp
- C++/TopologicalSort.cpp
Added Algorithm for Cycle Detection in a directed graph
> Cycle detection graph
